name: Lint

on:
  push:
    branches: 
      - main 
      - develop
  pull_request:
    branches: 
      - main 
      - develop

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
